version: '3.10'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - 8000:8000

  database:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=pguser
        - POSTGRES_PASSWORD=pgpass

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=suhaib@alembicsoft.com
      - PGADMIN_DEFAULT_PASSWORD=alembic123
      - SCRIPT_NAME=/pgadmin4
    restart: always
    links:
      - database
    ports:
      - 8082:80