# Generated by Django 4.0.5 on 2022-06-18 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('unit', models.CharField(max_length=64)),
                ('issueyear', models.DateField()),
                ('circability', models.BooleanField(default=True)),
                ('dissolved', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('collection', models.DateField()),
                ('imgF', models.FileField(upload_to='')),
                ('imgB', models.FileField(upload_to='')),
                ('notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
