# Generated by Django 4.0.4 on 2022-06-18 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='issueyear',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
