# Generated by Django 4.0.4 on 2022-06-18 07:31

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_currency_issueyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='imgB',
            field=models.FileField(upload_to='', validators=[app.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='imgF',
            field=models.FileField(upload_to='', validators=[app.validators.validate_file_extension]),
        ),
    ]
