# Generated by Django 4.0.4 on 2022-06-18 07:48

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_currency_imgb_alter_currency_imgf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='imgB',
            field=models.FileField(upload_to='static/uploads/', validators=[app.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='imgF',
            field=models.FileField(upload_to='static/uploads/', validators=[app.validators.validate_file_extension]),
        ),
    ]
