# Generated by Django 4.0.4 on 2022-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_currency_imgb_alter_currency_imgf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
